# hello-go-deploy-azure-app-service task-deploy.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-azure-app-service

run:
  path: ./hello-go-deploy-azure-app-service/ci/scripts/deploy.sh
  # args: [-debug]

