# hello-go-deploy-azure-app-service task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-azure-app-service

outputs:
- name: hello-go-deploy-azure-app-service-updated

run:
  path: ./hello-go-deploy-azure-app-service/ci/scripts/readme-github-pages.sh
  # args: [-debug]

